### PR TITLE
[PR-1] Deploy Terraform

### PR DESCRIPTION
**Pull request by woodonggyu**

### CODE REVIEW

**Comment by woodonggyu** [comment]
atlantis plan -p test

**Comment by woodonggyu** [comment]
Ran Plan for project: `test` dir: `account01/wafv2/ip-sets` workspace: `default`

<details><summary>Show Output</summary>

```diff

Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Finding hashicorp/aws versions matching ">= 4.24.0"...
- Installing hashicorp/aws v4.28.0...
- Installed hashicorp/aws v4.28.0 (signed by HashiCorp)

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_wafv2_ip_set.this[0] will be created
  + resource "aws_wafv2_ip_set" "this" {
      + addresses          = [
          + "1.1.1.1/32",
        ]
      + arn                = (known after apply)
      + description        = "GLOBAL"
      + id                 = (known after apply)
      + ip_address_version = "IPV4"
      + lock_token         = (known after apply)
      + name               = "ipset-iac-t1"
      + scope              = "REGIONAL"
      + tags               = {
          + "Service" = "Security"
        }
      + tags_all           = {
          + "Service" = "Security"
        }
    }

  # aws_wafv2_ip_set.this[1] will be created
  + resource "aws_wafv2_ip_set" "this" {
      + addresses          = [
          + "2.2.2.2/32",
          + "3.3.3.3/32",
        ]
      + arn                = (known after apply)
      + description        = "LOCAL - TEST1"
      + id                 = (known after apply)
      + ip_address_version = "IPV4"
      + lock_token         = (known after apply)
      + name               = "ipset-iac-t2"
      + scope              = "REGIONAL"
      + tags               = {
          + "Service" = "Security"
        }
      + tags_all           = {
          + "Service" = "Security"
        }
    }

  # aws_wafv2_ip_set.this[2] will be created
  + resource "aws_wafv2_ip_set" "this" {
      + addresses          = [
          + "4.4.4.4/32",
        ]
      + arn                = (known after apply)
      + description        = "LOCAL - TEST1"
      + id                 = (known after apply)
      + ip_address_version = "IPV4"
      + lock_token         = (known after apply)
      + name               = "ipset-iac-t3"
      + scope              = "REGIONAL"
      + tags               = {
          + "Service" = "Security"
        }
      + tags_all           = {
          + "Service" = "Security"
        }
    }

Plan: 3 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + aws_wafv2_ip_set_arn      = [
      + (known after apply),
      + (known after apply),
      + (known after apply),
    ]
  + aws_wafv2_ip_set_id       = [
      + (known after apply),
      + (known after apply),
      + (known after apply),
    ]
  + aws_wafv2_ip_set_tags_all = [
      + {
          + "Service" = "Security"
        },
      + {
          + "Service" = "Security"
        },
      + {
          + "Service" = "Security"
        },
    ]

─────────────────────────────────────────────────────────────────────────────

Note: You didn't use the -out option to save this plan, so Terraform can't
guarantee to take exactly these actions if you run "terraform apply" now.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p test`
* :put_litter_in_its_place: To **delete** this plan click [here](http://b29c94e6e7ee:4141/lock?id=woodonggyu%252Fterragrunt-aws-wafv2%252Faccount01%252Fwafv2%252Fip-sets%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p test`
</details>
Plan: 3 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by woodonggyu** [comment]
atlantis apply -p test

**Comment by woodonggyu** [comment]
Ran Apply for project: `test` dir: `account01/wafv2/ip-sets` workspace: `default`

**Apply Failed**: Pull request must be approved by at least one person other than the author before running apply.

**Review by s3ich4n — APPROVED** [review]
:+1:

**Comment by woodonggyu** [comment]
atlantis apply -p test

**Comment by woodonggyu** [comment]
atlantis unlock

**Comment by woodonggyu** [comment]
All Atlantis locks for this PR have been unlocked and plans discarded

**Comment by woodonggyu** [comment]
Ran Apply for project: `test` dir: `account01/wafv2/ip-sets` workspace: `default`

**Apply Error**
<details><summary>Show Output</summary>

```
running "terragrunt apply" in "/home/atlantis/.atlantis/repos/woodonggyu/terragrunt-aws-wafv2/12/default/account01/wafv2/ip-sets": signal: killed: running "terragrunt apply" in "/home/atlantis/.atlantis/repos/woodonggyu/terragrunt-aws-wafv2/12/default/account01/wafv2/ip-sets": 

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_wafv2_ip_set.this[0] will be created
  + resource "aws_wafv2_ip_set" "this" {
      + addresses          = [
          + "1.1.1.1/32",
        ]
      + arn                = (known after apply)
      + description        = "GLOBAL"
      + id                 = (known after apply)
      + ip_address_version = "IPV4"
      + lock_token         = (known after apply)
      + name               = "ipset-iac-t1"
      + scope              = "REGIONAL"
      + tags               = {
          + "Service" = "Security"
        }
      + tags_all           = {
          + "Service" = "Security"
        }
    }

  # aws_wafv2_ip_set.this[1] will be created
  + resource "aws_wafv2_ip_set" "this" {
      + addresses          = [
          + "2.2.2.2/32",
          + "3.3.3.3/32",
        ]
      + arn                = (known after apply)
      + description        = "LOCAL - TEST1"
      + id                 = (known after apply)
      + ip_address_version = "IPV4"
      + lock_token         = (known after apply)
      + name               = "ipset-iac-t2"
      + scope              = "REGIONAL"
      + tags               = {
          + "Service" = "Security"
        }
      + tags_all           = {
          + "Service" = "Security"
        }
    }

  # aws_wafv2_ip_set.this[2] will be created
  + resource "aws_wafv2_ip_set" "this" {
      + addresses          = [
          + "4.4.4.4/32",
        ]
      + arn                = (known after apply)
      + description        = "LOCAL - TEST1"
      + id                 = (known after apply)
      + ip_address_version = "IPV4"
      + lock_token         = (known after apply)
      + name               = "ipset-iac-t3"
      + scope              = "REGIONAL"
      + tags               = {
          + "Service" = "Security"
        }
      + tags_all           = {
          + "Service" = "Security"
        }
    }

Plan: 3 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + aws_wafv2_ip_set_arn      = [
      + (known after apply),
      + (known after apply),
      + (known after apply),
    ]
  + aws_wafv2_ip_set_id       = [
      + (known after apply),
      + (known after apply),
      + (known after apply),
    ]
  + aws_wafv2_ip_set_tags_all = [
      + {
          + "Service" = "Security"
        },
      + {
          + "Service" = "Security"
        },
      + {
          + "Service" = "Security"
        },
    ]

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: 


```
</details>

**Comment by woodonggyu** [comment]
atlantis plan -p test

**Comment by woodonggyu** [comment]
Ran Plan for dir: `account01/wafv2/ip-sets` workspace: `default`

**Plan Error**
<details><summary>Show Output</summary>

```
running "terragrunt plan" in "/home/atlantis/.atlantis/repos/woodonggyu/terragrunt-aws-wafv2/12/default/account01/wafv2/ip-sets": exit status 1: running "terragrunt plan" in "/home/atlantis/.atlantis/repos/woodonggyu/terragrunt-aws-wafv2/12/default/account01/wafv2/ip-sets": 
╷
│ Error: Error acquiring the state lock
│ 
│ Error message: ConditionalCheckFailedException: The conditional request
│ failed
│ Lock Info:
│   ID:        aacd8cdb-2571-d6ec-e6e9-5c1df532e10e
│   Path:      t-sec-iac-tfstate-bucket/account01/wafv2/ip-sets/terraform.tfstate
│   Operation: OperationTypeApply
│   Who:       atlantis@b29c94e6e7ee
│   Version:   1.2.4
│   Created:   2022-08-27 07:43:48.346929265 +0000 UTC
│   Info:      
│ 
│ 
│ Terraform acquires a state lock to protect the state from being written
│ by multiple users at the same time. Please resolve the issue above and try
│ again. For most commands, you can disable locking with the "-lock=false"
│ flag, but this is not recommended.
╵
time=2022-08-27T07:58:16Z level=error msg=Terraform invocation failed in /home/atlantis/.atlantis/repos/woodonggyu/terragrunt-aws-wafv2/12/default/account01/wafv2/ip-sets/.terragrunt-cache/3LCQstvLgaxQkTxS1l_xRW1M2Z0/VlHwk6InGESl7tP5DaihpJ-PBOQ/ipset prefix=[/home/atlantis/.atlantis/repos/woodonggyu/terragrunt-aws-wafv2/12/default/account01/wafv2/ip-sets] 
time=2022-08-27T07:58:16Z level=error msg=1 error occurred:
	* exit status 1




```
</details>

**Comment by woodonggyu** [comment]
atlantis plan -p test

**Comment by woodonggyu** [comment]
Ran Plan for dir: `account01/wafv2/ip-sets` workspace: `default`

**Plan Error**
<details><summary>Show Output</summary>

```
running "terragrunt plan" in "/home/atlantis/.atlantis/repos/woodonggyu/terragrunt-aws-wafv2/12/default/account01/wafv2/ip-sets": exit status 1: running "terragrunt plan" in "/home/atlantis/.atlantis/repos/woodonggyu/terragrunt-aws-wafv2/12/default/account01/wafv2/ip-sets": 

Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Finding hashicorp/aws versions matching ">= 4.24.0"...
- Installing hashicorp/aws v4.28.0...
- Installed hashicorp/aws v4.28.0 (signed by HashiCorp)

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
╷
│ Error: Error acquiring the state lock
│ 
│ Error message: ConditionalCheckFailedException: The conditional request
│ failed
│ Lock Info:
│   ID:        aacd8cdb-2571-d6ec-e6e9-5c1df532e10e
│   Path:      t-sec-iac-tfstate-bucket/account01/wafv2/ip-sets/terraform.tfstate
│   Operation: OperationTypeApply
│   Who:       atlantis@b29c94e6e7ee
│   Version:   1.2.4
│   Created:   2022-08-27 07:43:48.346929265 +0000 UTC
│   Info:      
│ 
│ 
│ Terraform acquires a state lock to protect the state from being written
│ by multiple users at the same time. Please resolve the issue above and try
│ again. For most commands, you can disable locking with the "-lock=false"
│ flag, but this is not recommended.
╵
time=2022-08-27T08:00:52Z level=error msg=Terraform invocation failed in /home/atlantis/.atlantis/repos/woodonggyu/terragrunt-aws-wafv2/12/default/account01/wafv2/ip-sets/.terragrunt-cache/3LCQstvLgaxQkTxS1l_xRW1M2Z0/VlHwk6InGESl7tP5DaihpJ-PBOQ/ipset prefix=[/home/atlantis/.atlantis/repos/woodonggyu/terragrunt-aws-wafv2/12/default/account01/wafv2/ip-sets] 
time=2022-08-27T08:00:52Z level=error msg=1 error occurred:
	* exit status 1




```
</details>

**Comment by woodonggyu** [comment]
atlantis plan -p test

**Comment by woodonggyu** [comment]
Ran Plan for project: `test` dir: `account01/wafv2/ip-sets` workspace: `default`

<details><summary>Show Output</summary>

```diff

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_wafv2_ip_set.this[0] will be created
  + resource "aws_wafv2_ip_set" "this" {
      + addresses          = [
          + "1.1.1.1/32",
        ]
      + arn                = (known after apply)
      + description        = "GLOBAL"
      + id                 = (known after apply)
      + ip_address_version = "IPV4"
      + lock_token         = (known after apply)
      + name               = "ipset-iac-t1"
      + scope              = "REGIONAL"
      + tags               = {
          + "Service" = "Security"
        }
      + tags_all           = {
          + "Service" = "Security"
        }
    }

  # aws_wafv2_ip_set.this[1] will be created
  + resource "aws_wafv2_ip_set" "this" {
      + addresses          = [
          + "2.2.2.2/32",
          + "3.3.3.3/32",
        ]
      + arn                = (known after apply)
      + description        = "LOCAL - TEST1"
      + id                 = (known after apply)
      + ip_address_version = "IPV4"
      + lock_token         = (known after apply)
      + name               = "ipset-iac-t2"
      + scope              = "REGIONAL"
      + tags               = {
          + "Service" = "Security"
        }
      + tags_all           = {
          + "Service" = "Security"
        }
    }

  # aws_wafv2_ip_set.this[2] will be created
  + resource "aws_wafv2_ip_set" "this" {
      + addresses          = [
          + "4.4.4.4/32",
        ]
      + arn                = (known after apply)
      + description        = "LOCAL - TEST1"
      + id                 = (known after apply)
      + ip_address_version = "IPV4"
      + lock_token         = (known after apply)
      + name               = "ipset-iac-t3"
      + scope              = "REGIONAL"
      + tags               = {
          + "Service" = "Security"
        }
      + tags_all           = {
          + "Service" = "Security"
        }
    }

Plan: 3 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + aws_wafv2_ip_set_arn      = [
      + (known after apply),
      + (known after apply),
      + (known after apply),
    ]
  + aws_wafv2_ip_set_id       = [
      + (known after apply),
      + (known after apply),
      + (known after apply),
    ]
  + aws_wafv2_ip_set_tags_all = [
      + {
          + "Service" = "Security"
        },
      + {
          + "Service" = "Security"
        },
      + {
          + "Service" = "Security"
        },
    ]

─────────────────────────────────────────────────────────────────────────────

Note: You didn't use the -out option to save this plan, so Terraform can't
guarantee to take exactly these actions if you run "terraform apply" now.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p test`
* :put_litter_in_its_place: To **delete** this plan click [here](http://b29c94e6e7ee:4141/lock?id=woodonggyu%252Fterragrunt-aws-wafv2%252Faccount01%252Fwafv2%252Fip-sets%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p test`
</details>
Plan: 3 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by woodonggyu** [comment]
atlantis apply -p test

**Comment by woodonggyu** [comment]
atlantis unlock

**Comment by woodonggyu** [comment]
All Atlantis locks for this PR have been unlocked and plans discarded

**Comment by woodonggyu** [comment]
Ran Apply for project: `test` dir: `account01/wafv2/ip-sets` workspace: `default`

**Apply Error**
<details><summary>Show Output</summary>

```
running "terragrunt apply" in "/home/atlantis/.atlantis/repos/woodonggyu/terragrunt-aws-wafv2/12/default/account01/wafv2/ip-sets": exit status 1: running "terragrunt apply" in "/home/atlantis/.atlantis/repos/woodonggyu/terragrunt-aws-wafv2/12/default/account01/wafv2/ip-sets": 

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_wafv2_ip_set.this[0] will be created
  + resource "aws_wafv2_ip_set" "this" {
      + addresses          = [
          + "1.1.1.1/32",
        ]
      + arn                = (known after apply)
      + description        = "GLOBAL"
      + id                 = (known after apply)
      + ip_address_version = "IPV4"
      + lock_token         = (known after apply)
      + name               = "ipset-iac-t1"
      + scope              = "REGIONAL"
      + tags               = {
          + "Service" = "Security"
        }
      + tags_all           = {
          + "Service" = "Security"
        }
    }

  # aws_wafv2_ip_set.this[1] will be created
  + resource "aws_wafv2_ip_set" "this" {
      + addresses          = [
          + "2.2.2.2/32",
          + "3.3.3.3/32",
        ]
      + arn                = (known after apply)
      + description        = "LOCAL - TEST1"
      + id                 = (known after apply)
      + ip_address_version = "IPV4"
      + lock_token         = (known after apply)
      + name               = "ipset-iac-t2"
      + scope              = "REGIONAL"
      + tags               = {
          + "Service" = "Security"
        }
      + tags_all           = {
          + "Service" = "Security"
        }
    }

  # aws_wafv2_ip_set.this[2] will be created
  + resource "aws_wafv2_ip_set" "this" {
      + addresses          = [
          + "4.4.4.4/32",
        ]
      + arn                = (known after apply)
      + description        = "LOCAL - TEST1"
      + id                 = (known after apply)
      + ip_address_version = "IPV4"
      + lock_token         = (known after apply)
      + name               = "ipset-iac-t3"
      + scope              = "REGIONAL"
      + tags               = {
          + "Service" = "Security"
        }
      + tags_all           = {
          + "Service" = "Security"
        }
    }

Plan: 3 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + aws_wafv2_ip_set_arn      = [
      + (known after apply),
      + (known after apply),
      + (known after apply),
    ]
  + aws_wafv2_ip_set_id       = [
      + (known after apply),
      + (known after apply),
      + (known after apply),
    ]
  + aws_wafv2_ip_set_tags_all = [
      + {
          + "Service" = "Security"
        },
      + {
          + "Service" = "Security"
        },
      + {
          + "Service" = "Security"
        },
    ]

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: 
Interrupt received.
╷
│ Error: error asking for approval: context canceled
Please wait for Terraform to exit or data loss may occur.
Gracefully shutting down...
│ 
│ 


╵

Two interrupts received. Exiting immediately. Note that data loss may have
occurred.

╷
│ Error: operation canceled
│ 
│ 
╵
time=2022-08-27T08:14:01Z level=error msg=Terraform invocation failed in /home/atlantis/.atlantis/repos/woodonggyu/terragrunt-aws-wafv2/12/default/account01/wafv2/ip-sets/.terragrunt-cache/3LCQstvLgaxQkTxS1l_xRW1M2Z0/VlHwk6InGESl7tP5DaihpJ-PBOQ/ipset prefix=[/home/atlantis/.atlantis/repos/woodonggyu/terragrunt-aws-wafv2/12/default/account01/wafv2/ip-sets] 
time=2022-08-27T08:14:01Z level=error msg=1 error occurred:
	* exit status 1




```
</details>

**Comment by woodonggyu** [comment]
atlantis plan -p test

**Comment by woodonggyu** [comment]
Ran Plan for project: `test` dir: `account01/wafv2/ip-sets` workspace: `default`

<details><summary>Show Output</summary>

```diff

Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Finding hashicorp/aws versions matching ">= 4.24.0"...
- Installing hashicorp/aws v4.28.0...
- Installed hashicorp/aws v4.28.0 (signed by HashiCorp)

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_wafv2_ip_set.this[0] will be created
  + resource "aws_wafv2_ip_set" "this" {
      + addresses          = [
          + "1.1.1.1/32",
        ]
      + arn                = (known after apply)
      + description        = "GLOBAL"
      + id                 = (known after apply)
      + ip_address_version = "IPV4"
      + lock_token         = (known after apply)
      + name               = "ipset-iac-t1"
      + scope              = "REGIONAL"
      + tags               = {
          + "Service" = "Security"
        }
      + tags_all           = {
          + "Service" = "Security"
        }
    }

  # aws_wafv2_ip_set.this[1] will be created
  + resource "aws_wafv2_ip_set" "this" {
      + addresses          = [
          + "2.2.2.2/32",
          + "3.3.3.3/32",
        ]
      + arn                = (known after apply)
      + description        = "LOCAL - TEST1"
      + id                 = (known after apply)
      + ip_address_version = "IPV4"
      + lock_token         = (known after apply)
      + name               = "ipset-iac-t2"
      + scope              = "REGIONAL"
      + tags               = {
          + "Service" = "Security"
        }
      + tags_all           = {
          + "Service" = "Security"
        }
    }

  # aws_wafv2_ip_set.this[2] will be created
  + resource "aws_wafv2_ip_set" "this" {
      + addresses          = [
          + "4.4.4.4/32",
        ]
      + arn                = (known after apply)
      + description        = "LOCAL - TEST1"
      + id                 = (known after apply)
      + ip_address_version = "IPV4"
      + lock_token         = (known after apply)
      + name               = "ipset-iac-t3"
      + scope              = "REGIONAL"
      + tags               = {
          + "Service" = "Security"
        }
      + tags_all           = {
          + "Service" = "Security"
        }
    }

Plan: 3 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + aws_wafv2_ip_set_arn      = [
      + (known after apply),
      + (known after apply),
      + (known after apply),
    ]
  + aws_wafv2_ip_set_id       = [
      + (known after apply),
      + (known after apply),
      + (known after apply),
    ]
  + aws_wafv2_ip_set_tags_all = [
      + {
          + "Service" = "Security"
        },
      + {
          + "Service" = "Security"
        },
      + {
          + "Service" = "Security"
        },
    ]

─────────────────────────────────────────────────────────────────────────────

Note: You didn't use the -out option to save this plan, so Terraform can't
guarantee to take exactly these actions if you run "terraform apply" now.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p test`
* :put_litter_in_its_place: To **delete** this plan click [here](http://dbe1f0c27cae:4141/lock?id=woodonggyu%252Fterragrunt-aws-wafv2%252Faccount01%252Fwafv2%252Fip-sets%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p test`
</details>
Plan: 3 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by woodonggyu** [comment]
atlantis apply -p test

**Comment by woodonggyu** [comment]
atlantis unlock

**Comment by woodonggyu** [comment]
All Atlantis locks for this PR have been unlocked and plans discarded

**Comment by woodonggyu** [comment]
Ran Apply for project: `test` dir: `account01/wafv2/ip-sets` workspace: `default`

**Apply Error**
<details><summary>Show Output</summary>

```
running "terragrunt apply" in "/home/atlantis/.atlantis/repos/woodonggyu/terragrunt-aws-wafv2/12/default/account01/wafv2/ip-sets": exit status 1: running "terragrunt apply" in "/home/atlantis/.atlantis/repos/woodonggyu/terragrunt-aws-wafv2/12/default/account01/wafv2/ip-sets": 

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_wafv2_ip_set.this[0] will be created
  + resource "aws_wafv2_ip_set" "this" {
      + addresses          = [
          + "1.1.1.1/32",
        ]
      + arn                = (known after apply)
      + description        = "GLOBAL"
      + id                 = (known after apply)
      + ip_address_version = "IPV4"
      + lock_token         = (known after apply)
      + name               = "ipset-iac-t1"
      + scope              = "REGIONAL"
      + tags               = {
          + "Service" = "Security"
        }
      + tags_all           = {
          + "Service" = "Security"
        }
    }

  # aws_wafv2_ip_set.this[1] will be created
  + resource "aws_wafv2_ip_set" "this" {
      + addresses          = [
          + "2.2.2.2/32",
          + "3.3.3.3/32",
        ]
      + arn                = (known after apply)
      + description        = "LOCAL - TEST1"
      + id                 = (known after apply)
      + ip_address_version = "IPV4"
      + lock_token         = (known after apply)
      + name               = "ipset-iac-t2"
      + scope              = "REGIONAL"
      + tags               = {
          + "Service" = "Security"
        }
      + tags_all           = {
          + "Service" = "Security"
        }
    }

  # aws_wafv2_ip_set.this[2] will be created
  + resource "aws_wafv2_ip_set" "this" {
      + addresses          = [
          + "4.4.4.4/32",
        ]
      + arn                = (known after apply)
      + description        = "LOCAL - TEST1"
      + id                 = (known after apply)
      + ip_address_version = "IPV4"
      + lock_token         = (known after apply)
      + name               = "ipset-iac-t3"
      + scope              = "REGIONAL"
      + tags               = {
          + "Service" = "Security"
        }
      + tags_all           = {
          + "Service" = "Security"
        }
    }

Plan: 3 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + aws_wafv2_ip_set_arn      = [
      + (known after apply),
      + (known after apply),
      + (known after apply),
    ]
  + aws_wafv2_ip_set_id       = [
      + (known after apply),
      + (known after apply),
      + (known after apply),
    ]
  + aws_wafv2_ip_set_tags_all = [
      + {
          + "Service" = "Security"
        },
      + {
          + "Service" = "Security"
        },
      + {
          + "Service" = "Security"
        },
    ]

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: 
Interrupt received.

Please wait for Terraform to exit or data loss may occur.
Two interrupts received. Exiting immediately. Note that data loss may have
Gracefully shutting down...

occurred.


╷
│ Error: error asking for approval: context canceled
│ 
│ 
╵
╷
│ Error: Error releasing the state lock
│ 
│ Error message: failed to retrieve lock info: unexpected end of JSON input
│ 
│ Terraform acquires a lock when accessing your state to prevent others
│ running Terraform to potentially modify the state at the same time. An
│ error occurred while releasing this lock. This could mean that the lock
│ did or did not release properly. If the lock didn't release properly,
│ Terraform may not be able to run future commands since it'll appear as if
│ the lock is held.
│ 
│ In this scenario, please call the "force-unlock" command to unlock the
│ state manually. This is a very dangerous operation since if it is done
│ erroneously it could result in two people modifying state at the same time.
│ Only call this command if you're certain that the unlock above failed and
│ that no one else is holding a lock.
╵
╷
│ Error: operation canceled
│ 
│ 
╵
time=2022-08-27T11:54:04Z level=error msg=Terraform invocation failed in /home/atlantis/.atlantis/repos/woodonggyu/terragrunt-aws-wafv2/12/default/account01/wafv2/ip-sets/.terragrunt-cache/3LCQstvLgaxQkTxS1l_xRW1M2Z0/VlHwk6InGESl7tP5DaihpJ-PBOQ/ipset prefix=[/home/atlantis/.atlantis/repos/woodonggyu/terragrunt-aws-wafv2/12/default/account01/wafv2/ip-sets] 
time=2022-08-27T11:54:04Z level=error msg=1 error occurred:
	* exit status 1




```
</details>

**Pull request closed without merging**
