### PR TITLE
[PR-5] Update config

### PR DESCRIPTION
**Pull request by woodonggyu**

### CODE REVIEW

**Comment by woodonggyu** [comment]
atlantis help

**Comment by woodonggyu** [comment]
```cmake
atlantis
Terraform Pull Request Automation

Usage:
  atlantis <command> [options] -- [terraform options]

Examples:
  # run plan in the root directory passing the -target flag to terraform
  atlantis plan -d . -- -target=resource

  # apply all unapplied plans from this pull request
  atlantis apply

  # apply the plan for the root directory and staging workspace
  atlantis apply -d . -w staging

Commands:
  plan     Runs 'terraform plan' for the changes in this pull request.
           To plan a specific project, use the -d, -w and -p flags.
  apply    Runs 'terraform apply' on all unapplied plans from this pull request.
           To only apply a specific plan, use the -d, -w and -p flags.
  unlock   Removes all atlantis locks and discards all plans for this PR.
           To unlock a specific plan you can use the Atlantis UI.
  approve_policies
           Approves all current policy checking failures for the PR.
  version  Print the output of 'terraform version'
  help     View help.

Flags:
  -h, --help   help for atlantis

Use "atlantis [command] --help" for more information about a command.
```

**Review by s3ich4n — APPROVED** [review]

**Comment by woodonggyu** [comment]
atlantis plan -p test

**Comment by woodonggyu** [comment]
Ran Plan for project: `test` dir: `account01/wafv2/ip-sets` workspace: `default`

<details><summary>Show Output</summary>

```diff

Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Finding hashicorp/aws versions matching ">= 4.24.0"...
- Installing hashicorp/aws v4.28.0...
- Installed hashicorp/aws v4.28.0 (signed by HashiCorp)

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_wafv2_ip_set.this[0] will be created
  + resource "aws_wafv2_ip_set" "this" {
      + addresses          = [
          + "1.1.1.1/32",
        ]
      + arn                = (known after apply)
      + description        = "GLOBAL"
      + id                 = (known after apply)
      + ip_address_version = "IPV4"
      + lock_token         = (known after apply)
      + name               = "ipset-iac-t1"
      + scope              = "REGIONAL"
      + tags               = {
          + "Service" = "Security"
        }
      + tags_all           = {
          + "Service" = "Security"
        }
    }

  # aws_wafv2_ip_set.this[1] will be created
  + resource "aws_wafv2_ip_set" "this" {
      + addresses          = [
          + "2.2.2.2/32",
          + "3.3.3.3/32",
        ]
      + arn                = (known after apply)
      + description        = "LOCAL - TEST1"
      + id                 = (known after apply)
      + ip_address_version = "IPV4"
      + lock_token         = (known after apply)
      + name               = "ipset-iac-t2"
      + scope              = "REGIONAL"
      + tags               = {
          + "Service" = "Security"
        }
      + tags_all           = {
          + "Service" = "Security"
        }
    }

Plan: 2 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + aws_wafv2_ip_set_arn      = [
      + (known after apply),
      + (known after apply),
    ]
  + aws_wafv2_ip_set_id       = [
      + (known after apply),
      + (known after apply),
    ]
  + aws_wafv2_ip_set_tags_all = [
      + {
          + "Service" = "Security"
        },
      + {
          + "Service" = "Security"
        },
    ]

─────────────────────────────────────────────────────────────────────────────

Saved the plan to: /home/atlantis/.atlantis/repos/woodonggyu/terragrunt-aws-wafv2/17/default/account01/wafv2/ip-sets/test-default.tfplan

To perform exactly these actions, run the following command to apply:
    terraform apply "/home/atlantis/.atlantis/repos/woodonggyu/terragrunt-aws-wafv2/17/default/account01/wafv2/ip-sets/test-default.tfplan"

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p test`
* :put_litter_in_its_place: To **delete** this plan click [here](http://aead6f97b2e3:4141/lock?id=woodonggyu%252Fterragrunt-aws-wafv2%252Faccount01%252Fwafv2%252Fip-sets%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p test`
</details>
Plan: 2 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by woodonggyu** [comment]
atlantis apply -p test

**Comment by woodonggyu** [comment]
Ran Apply for project: `test` dir: `account01/wafv2/ip-sets` workspace: `default`

<details><summary>Show Output</summary>

```diff
aws_wafv2_ip_set.this[1]: Creating...
aws_wafv2_ip_set.this[0]: Creating...
aws_wafv2_ip_set.this[1]: Creation complete after 0s [id=d91b8258-234f-4a47-8e24-5734ab49a115]
aws_wafv2_ip_set.this[0]: Creation complete after 0s [id=6240eddf-47b7-4f12-bbb3-9a61d0175c26]

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.

Outputs:

aws_wafv2_ip_set_arn = [
  "arn:aws:wafv2:ap-northeast-2:362252864672:regional/ipset/ipset-iac-t1/6240eddf-47b7-4f12-bbb3-9a61d0175c26",
  "arn:aws:wafv2:ap-northeast-2:362252864672:regional/ipset/ipset-iac-t2/d91b8258-234f-4a47-8e24-5734ab49a115",
]
aws_wafv2_ip_set_id = [
  "6240eddf-47b7-4f12-bbb3-9a61d0175c26",
  "d91b8258-234f-4a47-8e24-5734ab49a115",
]
aws_wafv2_ip_set_tags_all = [
  tomap({
    "Service" = "Security"
  }),
  tomap({
    "Service" = "Security"
  }),
]

```
</details>

**Comment by woodonggyu** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `account01/wafv2/ip-sets` workspace: `default`

**Pull request merged**
