### PR TITLE
[PR-2] Update Config

### PR DESCRIPTION
**Pull request by woodonggyu**

### CODE REVIEW

**Comment by woodonggyu** [comment]
atlantis help

**Comment by woodonggyu** [comment]
```cmake
atlantis
Terraform Pull Request Automation

Usage:
  atlantis <command> [options] -- [terraform options]

Examples:
  # run plan in the root directory passing the -target flag to terraform
  atlantis plan -d . -- -target=resource

  # apply all unapplied plans from this pull request
  atlantis apply

  # apply the plan for the root directory and staging workspace
  atlantis apply -d . -w staging

Commands:
  plan     Runs 'terraform plan' for the changes in this pull request.
           To plan a specific project, use the -d, -w and -p flags.
  apply    Runs 'terraform apply' on all unapplied plans from this pull request.
           To only apply a specific plan, use the -d, -w and -p flags.
  unlock   Removes all atlantis locks and discards all plans for this PR.
           To unlock a specific plan you can use the Atlantis UI.
  approve_policies
           Approves all current policy checking failures for the PR.
  version  Print the output of 'terraform version'
  help     View help.

Flags:
  -h, --help   help for atlantis

Use "atlantis [command] --help" for more information about a command.
```

**Comment by woodonggyu** [comment]
atlantis plan -p test

**Review by s3ich4n — APPROVED** [review]

**Comment by woodonggyu** [comment]
Ran Plan for dir: `account01/wafv2/ip-sets` workspace: `default`

**Plan Error**
<details><summary>Show Output</summary>

```
running "terragrunt plan" in "/home/atlantis/.atlantis/repos/woodonggyu/terragrunt-aws-wafv2/13/default/account01/wafv2/ip-sets": exit status 1: running "terragrunt plan" in "/home/atlantis/.atlantis/repos/woodonggyu/terragrunt-aws-wafv2/13/default/account01/wafv2/ip-sets": 

Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.
Error refreshing state: state data in S3 does not have the expected content.

This may be caused by unusually long delays in S3 processing a previous state
update.  Please wait for a minute or two and try again. If this problem
persists, and neither S3 nor DynamoDB are experiencing an outage, you may need
to manually verify the remote state and update the Digest value stored in the
DynamoDB table to the following value: 

time=2022-08-27T08:40:53Z level=error msg=Terraform invocation failed in /home/atlantis/.atlantis/repos/woodonggyu/terragrunt-aws-wafv2/13/default/account01/wafv2/ip-sets/.terragrunt-cache/3CPq7-_2g0p-Ortcu8RiUMbTjW4/ia4an0-lMsDSp6EWuOajMUicSUY/ipset prefix=[/home/atlantis/.atlantis/repos/woodonggyu/terragrunt-aws-wafv2/13/default/account01/wafv2/ip-sets] 
time=2022-08-27T08:40:53Z level=error msg=1 error occurred:
	* exit status 1




```
</details>

**Comment by woodonggyu** [comment]
atlantis plan -p test

**Comment by woodonggyu** [comment]
Ran Plan for dir: `account01/wafv2/ip-sets` workspace: `default`

**Plan Error**
<details><summary>Show Output</summary>

```
running "terragrunt plan" in "/home/atlantis/.atlantis/repos/woodonggyu/terragrunt-aws-wafv2/13/default/account01/wafv2/ip-sets": exit status 1: running "terragrunt plan" in "/home/atlantis/.atlantis/repos/woodonggyu/terragrunt-aws-wafv2/13/default/account01/wafv2/ip-sets": 

Initializing the backend...
Error refreshing state: state data in S3 does not have the expected content.

This may be caused by unusually long delays in S3 processing a previous state
update.  Please wait for a minute or two and try again. If this problem
persists, and neither S3 nor DynamoDB are experiencing an outage, you may need
to manually verify the remote state and update the Digest value stored in the
DynamoDB table to the following value: 

time=2022-08-27T08:42:29Z level=error msg=Terraform invocation failed in /home/atlantis/.atlantis/repos/woodonggyu/terragrunt-aws-wafv2/13/default/account01/wafv2/ip-sets/.terragrunt-cache/3CPq7-_2g0p-Ortcu8RiUMbTjW4/ia4an0-lMsDSp6EWuOajMUicSUY/ipset prefix=[/home/atlantis/.atlantis/repos/woodonggyu/terragrunt-aws-wafv2/13/default/account01/wafv2/ip-sets] 
time=2022-08-27T08:42:29Z level=error msg=1 error occurred:
	* exit status 1




```
</details>

**Pull request closed without merging**
